### ISSUE TITLE
Update Species Presence Section

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#101]
Following July 28th 2022 meeting with Adrian, the following should be updated in the species presence section of the RR:
 - Data use constraint for all should be: For environmental response use only.
 - Add a presence column dependent on today's date to the data tables.

**Comment by gomezcatalina** [comment]
For environmental response use only: interesting caveat. Does that mean Lindsay Brager should not use it for aquaculture?

**Comment by stoyelq** [comment]
That was Adrian's take on this data, it was not designed to be informative to other processes. So if it says a species is present, that is in the context of environmental response, and not necessarily a well verified presence report like the RV survey or rockweed data..  It is Open Data, so I am okay including it and making that caveat obvious, and if Lindsay wants to follow up on it with Adrian she can do so.
