### ISSUE TITLE
Connect SAR Search tool to RR

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#104]
# Proposed Change/Activity
SAR Search Tool developed in Gulf region hosts important information, in part, form a literature review of COSEWIC reports. Team interested in integrating with RR.

# Why is this important
Supporting process of making all relevant info for SAR species in the report is key

# Additional Context
Team in Gulf Region interested in integrating their data with the tool. Quentin and Catalina supporting these conversations
@stoyelq connected to SARA DM apps tool/ Quentin set up an application program interface (API) for Donald Pirie-Hay so they can download the data as needed.

# proposed Action Items 
 
- [x] @gomezcatalina and @stoyelq to develop some text to incorporate in the report to include this data
- [ ]  To schedule a meeting once these components are ready to review them together and explore next steps
- [x] To decide whether we want move this to the dreaming phase and work on it later on - thoughts @stoyelq?

**Comment by stoyelq** [comment]
This is already about 50% done, so I was just going to complete it out of momentum. Donald Pirie-Hay et al. have already provided the following disclaimers for the text of this section: 

Disclaimers for SAR Search App data within the Spatial Reproducible Reporting Tool 
3-Jun-2022
Species at Risk Program, Gulf Region. DFO
Donald Pirie-Hay and Isabelle Thériault

-	The data originates from both external and internal sources, and must not to be shared or used outside DFO. 
-	The data is not comprehensive in any way. It is likely that there are records of occurrence for any given species that have not been included or represented and likely does not represent the latest records, findings, or distribution for any given species. 
-	Although the data is accurate based on its original source, it is from a variety of sources and varies in quality depending on the source for any given record.
-	While every reasonable effort has been made to ensure that the data is correct, DFO Species at Risk Program does not warrant or guarantee the accuracy, completeness, or currency of the data for any specific use. 
-	Data that are represented only by “Regions” in the record and/or the map only implies that the species has been found in the specified region(s). “Regions” must not be used as polygons of distribution.
-	A data point can either represent the exact location at which a species was found or may be used to indicate the presence of a species in any given waterbody. Please consult all information for any given record before making any interpretation.

**Comment by stoyelq** [comment]
Should these be getting filtered by year as well? There are ~600 total records and only about ~150 that are after 2010
