### ISSUE TITLE
Create a local copy of the RR data

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#130]
### Action
Copy the remote data into the local repo.  The data lives on the IN drive: R:\Science\BIODataSvc\IN\MSP\Data\RData\data and the contents of this  "data"  directory should align with you local version of the repository: here::here("app/data").  There is a script that will do this, but it's much quicker to just cut and paste the file the first time because it's got ~250GB of data in it.  

### Effort:
1.  It's cut and pasting at it's finest.

**Comment by PJCoates** [comment]
Data copied over and ticket closed
