### ISSUE TITLE
RR-Revamp-Update PR for RR

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#132]
# Proposed Activity

To update main communication tools for RR: Presentation & Project Planning Tool

# Why is this important?

Important to communicate new era of RR

# Action Items

- [x] Update power point presentation [here](https://086gc.sharepoint.com/:p:/s/MaritimesSpatialPlanning-MAROpenDataLogistics/EUl72oB9_WREtmXSGizIhi4BXP6Oc9VkWCWt__Y2ALQu0g)
- [x] Product owners to give blessing
- [x] dev team to give blessing: 
@stoyelq @PJCoates & @BBowerDFO 
- [x] Update project planning tool - send draft to all PIs.

**Comment by stoyelq** [comment]
It looks good to me; I just made a couple small changes (and used my influencer power to add Jake to the steering committee).

**Comment by BBowerDFO** [comment]
Presentation looks great
