### ISSUE TITLE
Update NARWC Dataset

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#136]
## Proposed activity

Updating NARWC

## Why this is important

Updating tools as much as possible before end of 2022

## Action items

- [x] Replace narwc <- read.csv(file.path(fileLoadPath, "NaturalResources/Species/Cetaceans/NARWC/NARWC_09-18-2020.csv"), stringsAsFactors = FALSE) in [preprocessing pipeline](https://github.com/dfo-mar-odis/shinySpatialApp/blob/main/reports/sections/narwc/narwc_preprocessing.R) with Catalina Gomez Canada cetaceans Ver2 02-23-2022.xlsx
- [x] Catalina to document how to do next request in the spring

**Comment by stoyelq** [comment]
So it looks like `narwcExcel <- readxl::read_excel(file.path(fileLoadPath, "NaturalResources/Species/Cetaceans/NARWC/NARWC_02-23-2022.xlsx"))
` will do the trick of importing the file, but there also seem to be a couple of new column headers that might make a mess of things. 

There is not a ton of processing that happens for this dataset, mainly merges with the species names and cetLegend table which should still work.  

So @PJCoates, time permitting:
- [ ] create a new branch
- [ ]  add in the new line 
- [ ] double check that everything still works with the new data as it should.  The things to check are that the final narwc_sf object has the same format/headers and that the report section still knits.  
- [ ] commit the changes and push the branch to the repo
- [ ] file a PR  and tag me as a reviewer on it.

### Effort:
5?  Once your comfortable with the process this should be a 2-3

**Comment by PJCoates** [comment]
Changes between new and old files:

1) .xlsx vs csv format
2) IDSOURCE column added
3) Changes to header formats: DATE TYPE vs DATATYPE, ID_RELIABILITY vs ID

**Comment by stoyelq** [comment]
Jake and Catalina to discuss updating options in the spring.
