### ISSUE TITLE
Updating Habitat/Planning section in RR

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#141]
## Proposed activity

Habitat section can be largely enhanced by highly desired sections available in Open Data

## Why this is important

"Important for many reasons, there is currently no information on benthic habitat Corals and Sponges in the Reproducible Report. Construction activities, turbine foundations, and environmental pollutants can impact benthic habitat". Product Owners

## Action items

The [metadata spreadsheet](https://086gc.sharepoint.com/:x:/r/sites/MaritimesSpatialPlanning-MAROpenDataLogistics/_layouts/15/doc2.aspx?sourcedoc=%7BCC28C21B-5BBD-4E38-A9A7-D96363B806D8%7D&file=ReproducibleReporting-Data-Metadata.xlsx&action=default&mobileredirect=true&cid=27e0e480-78f6-4d92-9d99-819317eeabab) highlight where this new info should be added (around rows 34/35)

- [x] A substrate classification for the Inshore Scotian Shelf and Bay of Fundy, Maritimes Region
- [x] Delineation of Coral and Sponge Significant Benthic Areas in Eastern Canada [Open Data record](https://open.canada.ca/data/en/dataset/6af357a3-3be1-47d5-9d1f-e4f809c4c903) 

![Image](https://user-images.githubusercontent.com/21310429/204802397-d4306a24-0a2f-4015-a002-1eeb444e6c97.png)

- [x] NO DATA ON MARITIMES -- to confirm with Javier. Kernel Density Analyses of Coral and Sponge Catches from Research Vessel Survey Data for Use in Identification of Significant Benthic Areas https://open.canada.ca/data/en/dataset/fb1d1c3d-ba6e-4d0d-b629-f4f497edc10f
- [x] Other effective area-based conservation measures https://open.canada.ca/data/en/dataset/44769543-7a23-4991-a53f-c2cf7c7a946f Warning: this is a new record that would impact current section titled: Draft Conservation Network Design"

**Comment by PJCoates** [comment]
"Substrate classification", "Significant coral and sponge benthic areas", and "Other effective conservation measures" sections have been added to main. Thanks Quentin for all of your guidance and help with getting me up to speed on this!!
