### ISSUE TITLE
Connecting to SARA geodatabase sde :earth_americas:

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#52]
# Proposed Change/Activity

Link to the SDE database connection to load in draft critical habitat, under consideration species, Ontario point layer data (lower priority).

# Why is this important

- We want to avoid engagement overload 
- We want to support each other
- We want to streamline work

# Additional Context

Working with C. Bakelaar's team

**Comment by gomezcatalina** [comment]
Updating with new format for consistency

**Comment by stoyelq** [comment]
Not done yet : )

**Comment by stoyelq** [comment]
- [ ] Get all data from merged level
- [ ] See if it comes from mapserver
- [ ] Add population column to listed species table + fix table join
- [ ] GEORA layer: detailed coastline,  from NRCAN

- [ ] Under consideration / draft crithab for use in DFO only
- [ ] Write R Script to crop SDE data on the way out of the merged Layer in SDE
- [ ] Look into getting access to SDE services
- [ ] See if anyone else should be able to run the report
