### ISSUE TITLE
New content: Data mining - SARA permits section 73

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#62]
# Proposed Change/Activity

To incorporate data mining from SARA Permits Section 73 into reproducible reporting.

# Why is this important

Great opportunity for additional information rescued by Charlotte Smith

# Additional Context

In support of the expansion and integration of additional data sources, Species at Risk records from Section 73 permits were mined and summarized I this section for internal DFO needs. Information extracted from the reports includes relevant details on Species at Risk interactions that occurred under specific permits. In the excel file, the following information is being compiled: Year, Month, Day, Latitude, Longitude, Water Body, Species, Number of Individuals, Project Activity and Permit Report Number (please refer to the screen capture below for an example). Permit Report Number allows authorized DFO staff to review the permit files if required; protected information is not part of the data mining exercise. Latitude and longitude formats differ between reports; therefore, all coordinates are being converted to LatDD and LongDD format to promote consistency. In the case that report records are inconclusive (species is unknown), they are omitted from the spreadsheet.

Useful info available here: https://www.canada.ca/en/environment-climate-change/services/species-risk-public-registry/policies-guidelines/permitting-under-section-73.html

**Comment by stoyelq** [comment]
- How are we handling data for sea turtles? For OBIS, we didn't include them, and I can't remember exactly why.

> Will filter out the sea turtle data before adding to report.

- Should this section also be split into Fish/Invertebrates and Cetaceans? There's data for both

> Will get dealt with in #68
