### ISSUE TITLE
Multi-sectorial collaboration

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#67]
# Proposed Change/Activity

To develop a board / plan to share, when appropriate, data and information between Spatial Reproducible Reporting Tool (Science), and GIS tool (IM-FFHPP). 

# Why is this important

- We want to avoid engagement overload (request data updates as a batch for multiple purposes e.g. RR tool, GIS tool, MSP atlas, Open Data, MCT needs)
- We want to support each other
- We want to streamline work

# Additional Context
This will take a bit of time and communication with different folks about how to tackle it.

May 2 2022 meeting with S. Butler:
- GIS team with IM&TS -- we should be able to access their new server, and we could access the map services. Some data can be published as part of the web mapping service. Enterprise GIS system - you assign different groupings of staff. Different options: 1) we add a list of staff that have access? or 2) internal to DFO. B. Bower doing this process for ASF.

June 13 2022 meeting (Gomez, Butler, Coffen-Smout, Thompson, Wamboldt)
Sectors to co-organize a regional information session on July 8th, followed by a case study about how we could all pull information together using different tools and approaches (IM tools, MSP atlas, Reproducible reporting, Whale Insight app etc). 

Action items:

- [x] Send Sean list of who can have access to the GIS tool
- [x] Sean to ask IT about Protected B data in the GIS server; Update: Sean confirmed Protected B data can be included. 
- [x] Catalina to touch base with Mike and Claire to discuss options for MARFIS/ISDB (done in May 2022)
- [x] Stephen to send to Sean/Jennifer data and text of Charlotte's data mining exercise for their review (encrypted email)
- [x] Quentin to schedule follow-up meeting to touch base on progress 
- [x] Create updated workflow to incorporate GIS tool into data pipelines
- [x] Brian to identify additional Open Data sources for multi-sectorial tool event on July 8th 
- [x] To add those extra data sources in the RR to support the multi-sectorial tool event

July 8 2022 - presentation to Regulatory Review team
- MSP Public launch atlas in Jan 2023 - priorities for open data, transparency decision-making. 
- Let's coordinate on data!!!! that's the most important part of all of this

**Comment by stoyelq** [comment]
June 9th Meeting agenda:

Updates: 
R workflow works mostly fine, need to generate a token, but there's an API for that.

putting Charlotte's Data up: Sean will publish this in the SRRT group

Data storage vs sharing: storage is okay if this is small.

Actions:
- [ ] Quentin to finalize potential workflow for allowing access for other folks to generate protected reports
- [ ] Sean to publish Charlotte's data will trigger next meeting once Rémi will return
