### ISSUE TITLE
RAP Battle Agenda

### ISSUE THREAD

**Issue by stoyelq** [dfo-mar-odis/shinySpatialApp#81]
**Proposed Action Items**

May 12 2022

- [x] @jdpye to explore whether _spent_ or _estimate_ from Gitlab are also available in GitHub

- All to come up with themes for a potential session during  [Ocean Hack week](https://oceanhackweek.github.io/) (in the context of conservation planning?) e.g. 
      - [Project planning for developers](https://github.com/features/issues), 
      - Formalized tickets rules (and keep learning from @jackVanish) 
      - Running the Spatial Reproducible Reporting Tool,
      - Open call for teams to integrate new data/modules into the Spatial Reproducible Reporting tool? 

@gomezcatalina will develop an issue task list for data updates, to be implemented on an annual basis -- thanks Jon and Bruce for the inspiration.

**Proposed Agenda for RAP battle** :microphone: :level_slider: :headphones:
_Feel free to comment, update and propose other items!_

 **- Tour of report updates: new app with region selector, new repo layout, fixed (removed) renv**

 **- RAP Project Board for workflow management, with examples of where the project is going:**
   - Cumulative impact mapping with Noreen, Grace, and David
   - Integration with DFO's GIS server to help serve internal data (in addition to Open Data)
   - Working with other internal tools (e.g. SARA SDE, and SARA application in DM apps)
   
 **- OBIS! Teams updates**
   - Linkage between Open Data and OBIS
   - eDNA into OBIS
   - Other?
   
 - Philosophical discussion on whether to create an **open version of the reports**: is there risk of overlap with other tools under-development?

**Comment by jdpye** [comment]
Unfortunate that /spend and /estimate are not GitHub actions, but there are some git-related time-tracking tools out there. Nothing I can recommend, though :(

**Comment by remi-daigle** [comment]
Yep, lots of add-on type things seem to be available: https://github.com/marketplace/category/time-tracking
But I haven't used, tested, or read about any of them!
