### ISSUE TITLE
New content: Isle Madame

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#90]
Add Open Data records identified by Brian into the RR:

Here are some records in the Isle Madame area. 

- [x] [A Novel Video and Acoustic Survey of the Seaweeds of Isle Madame - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/ebdd8f91-9131-45f0-8aec-aba9f65e3fae)

The follow have a polygon for the Port Hawkesbury region as well as the Bay of Fundy. All are downloadable. 

- [x] [Oceans Protection Plan Regional Response Planning Extents - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/f32ce23d-4a16-4eaa-9648-2f02a98b91af)

- [x] [Bluefin Tuna Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/0c3b25df-f831-43e8-a8ac-336e1467c4fe)

- [x] [Bottlenose Whale Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/29dd835b-7c96-4c62-b558-275dfe13cbe9)

- [x] [North Atlantic Right Whale Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/d159ac68-6e46-44b5-a4e9-951880892c63)

- [x] [Finback Whale Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/7e2f85b3-19eb-4ecf-8557-69c8df1bc084)

- [x] [Harbour Porpoise Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/58ea48ab-f052-48ab-9c18-4353e51b8bea)

- [x] [Harbour Seal Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/5bbc1575-4267-44fa-ae35-ee08cc2af8fb)

- [x] [American Lobster Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/47bf4555-ce3c-492f-a367-a6eab1862970)

- [x] [Snow Crab Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/edb15c7b-d901-46b0-a460-1aca22c013ea)

- [x] [Atlantic Salmon Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/436cdf90-9d6b-4784-938b-feec48844a67)

- [x] [Salmon Rivers Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/ded53eaa-bb98-4476-beea-3138372c740b)

- [x] [Soft Shelled Clams Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/59121e8f-0acc-411a-99cb-54980df10ba6)

- [x] [Grey Seal Presence, Maritimes Region - Open Government Portal (canada.ca)](https://open.canada.ca/data/en/dataset/e73c90ff-0ab6-4257-8d6d-3dfc46fc0dc5)

- [x] https://gisd.dfo-mpo.gc.ca/portal/home/webmap/viewer.html?webmap=439802012d84467bb042a9d726cab572&extent=-61.2266,45.5128,-61.1255,45.5463   

Netforce internal layer ( you can access it for now)  It is titled “Defence RD Canada – Janvrin Island Presence Absence V2”

**Comment by stoyelq** [comment]
Just need an abstract out of  [the last one](https://gisd.dfo-mpo.gc.ca/portal/home/webmap/viewer.html?webmap=439802012d84467bb042a9d726cab572&extent=-61.2266,45.5128,-61.1255,45.5463)
