### ISSUE TITLE
Update content - ISDB & MARFIS

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#98]
## Proposed Change/Activity

Publishing aggregated data from the Maritime Fishery Information System (MARFIS) and Industry Survey Database (ISDB) in the eGIS Internal server (dev test / GISD) for DFO access only

## Why is this important

eGIS Internal server (dev test / GISD) is maximizing our efficiency to organize and update data for the Spatial RR tool and Sean's GIS tool in support of decision making

## Additional Context

Need to proceed with caution as this is Protected B data.

## Updates and Tasks 

- [x] @MMMcMahon to extract data 
- [x] @Bower1 to confirm security assessment requirements with E. Mesner
- [x] @gomezcatalina to compile text for the description of this record 
- [x] All to approve text [here](https://086gc.sharepoint.com/:w:/s/MaritimesSpatialPlanning-MAROpenDataLogistics/EVOcxfygRr9Jl2WqtHahDsoBl-1XdxpmXeMwk-RL5KGn-w?e=1onIat). 
- [x] All to define privileges: limited access to folks in Reproducible Reporting and Sean Butler GIS tool. 
- [x] Code: @MMMcMahon to confirm whether code could be stored in the RR repo https://github.com/dfo-mar-odis/shinySpatialApp/tree/main/reports/sections/isdb-marfis? Or is there another repo? --- dealt with in #100 
- [x] All: to explore whether we could include a link to the repo in the eGIS publication 
- [x] Statements of security: to decide whether we could add a link so staff can access the statements of security to publish this as a complete package. 
- [x] Brian to send additional data to Colin and Claire for final review
- [x] @BBowerDFO to publish MARFIS/ISDB in the eGIS Internal server (dev test / GISD) for DFO access only (approved by Clair and Colin on September 15 2022)

**Comment by MMMcMahon** [comment]
@gomezcatalina - with respect to the code storage you're asking about - you're referring to [this](https://086gc-my.sharepoint.com/:u:/g/personal/mike_mcmahon_dfo-mpo_gc_ca/EZ0vXEwVnMpOm0rzkZl8I8oBzjpcaqVFHgCSggnULEsrLQ?e=UM8efw)?  There's nothing private there - you can store it in the dfo-mar-odis repo.  :)
