### ISSUE TITLE
Updates MARFIS/ISDB content in RR

### ISSUE THREAD

**Issue by gomezcatalina** [dfo-mar-odis/shinySpatialApp#99]
# Proposed Change/Activity

to update RR with new API of MARFIS and ISDB once #98 is closed.

# Why is this important

eGIS Internal server (dev test / GISD) is maximizing our efficiency to organize and update data for the Spatial RR tool and Sean's GIS tool in support of decision making - using APIs is the best solution so far!

# Additional Context

Need to proceed with caution as this is Protected B data.

# To do

- [x] @stoyelq (?) to update RR with new API once #98 is closed - 
- [x] see #100 as some code may not be obsolete due to Mike's new awesome script
- [x] @stoyelq add  CONFIDENTIAL – AN ASSESSMENT IS REQUIRED BEFORE PUBLIC RELEASE.  text to marfis/isdb plots and section headers.

# Percieved Effort
8?

**Comment by stoyelq** [comment]
Email sent to project leads for feedback, will close once they approve the section
